name: 刷课

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * *'   # 每天早上 8 点，可改成凌晨 '0 3 * * *'

jobs:
  Start:
    runs-on: ubuntu-latest
    
    steps:
      - name: 拷贝代码
        uses: actions/checkout@v6   # 升级到最新 v6

      - name: 设置 Python 环境
        uses: actions/setup-python@v6   # ← 关键！必须升级到 v6
        with:
          python-version: '3.13'

      - name: 安装依赖包
        run: pip install -r ./requirements.txt

      - name: 执行刷课脚本
        env:
          CHAOIXING_USERNAME: ${{ secrets.CHAOXING_USERNAME }}
          CHAOIXING_PASSWORD: ${{ secrets.CHAOXING_PASSWORD }}
          CHAOIXING_COURSE_LIST: ${{ secrets.CHAOXING_COURSE_LIST }}
        run: python main.py -u "\( {17311328007}" -p " \){lwh070909}" -l "${261044256}"
